### ISSUE TITLE
CSS styles can leak into the Lamdera Live overlay

### ISSUE THREAD

**Issue by edkelly303** [lamdera/compiler#37]
**Quick Summary:**
The `<a>` element in the overlay that links to the Lamdera docs can inherit styles from the app's CSS, as in this screenshot:

![image](https://github.com/user-attachments/assets/48e019c7-56c0-4f91-ba17-eca2475fbc1c)

## SSCCE

Here's the CSS that causes this, which is in `public/styles.css` in my repo:

```css
a:not(nav *) {
    border-color: var(--acnt-07-bd);
    background-color: var(--acnt-03-el);
    border-radius: 5px;
    border-width: 2px;
    border-style: solid;
    text-decoration: none;
    padding: 5px;
}
```

- **Elm:** 19.1 / Lamdera 1.3.2
- **Browser:** Firefox
- **Operating System:** Nixos

## Additional Details
N/A
